[build]
    functions = "functions"
    publish = "build"
    command = "npm run build"

[dev]
    framework = "#custom"
    command = "npm run dev:snowpack"
    targetPort = 8079
    port = 8080
    publish = "publish"
    autoLaunch = true

